package com.smartfleet.smartfleet.entity;

public enum AuditEventType {
    MISSION_CREATED,
    MISSION_ASSIGNED,
    MISSION_STARTED,
    MISSION_RETURNED,
    MISSION_VALIDATED,
    MISSION_SENT_TO_MAINTENANCE,
    MISSION_CONFLICT_REJECTED,
    FUEL_RECORDED,
    USER_CREATED,
    USER_DELETED,
    VEHICLE_CREATED,
    DRIVER_CREATED,
    LOGIN_SUCCESS,
    LOGIN_FAILED
}
